"""Render the shared activity plan and its optional two-car branches."""
from pathlib import Path
import re
import markdown
ROOT=Path(__file__).resolve().parents[1]
source=(ROOT/'planning/activities-handoff-2026-09-26.md').read_text()
body=markdown.markdown(source,extensions=['tables'])
parts=re.split(r'(<h2>.*?</h2>)',body)
sections=[]
keys=['overview','29','30','01','02','03','04','extend','book','audit']
labels=['总览','9/29','9/30','10/1','10/2','10/3','10/4','个人延长','预约与预算','核查记录']
intro=parts[0]
for i in range(1,len(parts),2):
    j=(i-1)//2
    sections.append(f'<section id="day-{keys[j]}" data-day="{keys[j]}">{parts[i]}{parts[i+1]}</section>')
nav='<button type="button" data-filter="all" aria-pressed="true">全部</button>'+''.join(f'<button type="button" data-filter="{k}" aria-pressed="false">{v}</button>' for k,v in zip(keys,labels))
style='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f4f2ec;color:#18332e;font:16px/1.85 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{background:#173b35;color:#fff;padding:40px max(5vw,20px)}header h1{max-width:1100px;margin:auto}header p{max-width:1100px;margin:10px auto;color:#e2ede7}main{max-width:1160px;margin:auto;padding:24px}h1{font-size:clamp(26px,4vw,40px);line-height:1.4}h2{margin-top:40px;border-top:1px solid #bdcec0;padding-top:24px;font-size:26px}h3{margin-top:28px}a{color:#146954}table{display:block;overflow:auto;border-collapse:collapse;margin:20px 0;width:100%;background:#fff}th,td{padding:12px 16px;border:1px solid #d9e2db;vertical-align:top;min-width:140px}th{background:#e5ece4}strong{color:#153e33}.nav{position:sticky;top:0;background:#fffef7f5;padding:10px 20px;display:flex;gap:8px;overflow:auto;z-index:2;border-bottom:1px solid #ddd}button{font:inherit;cursor:pointer;white-space:nowrap;background:white;color:#173b35;border:1px solid #b8cec0;border-radius:24px;padding:6px 14px}button[aria-pressed=true]{background:#173b35;color:white}button:focus-visible,a:focus-visible{outline:3px solid #b87513;outline-offset:3px}section{scroll-margin-top:90px}[hidden]{display:none!important}.branchbox{background:white;border:1px solid #c9d7ca;border-radius:16px;padding:22px;margin:24px 0}.branchbox h2{margin:0;padding:0;border:0}.branch-controls{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.lanes{display:grid;grid-template-columns:1fr 1fr;gap:14px}.lane{padding:18px;background:#e8f1ea;border-left:5px solid #376b54;border-radius:9px}.lane.friend{background:#eef1f8;border-color:#51688f}.nodes{display:flex;flex-direction:column;gap:7px}.node{background:white;padding:10px;border-radius:8px}.arrow{text-align:center;color:#6b7d70}.rendezvous{text-align:center;margin-top:15px;padding:12px;background:#fff0cf;border-radius:8px}.caption{color:#617369;font-size:14px}.source-link{padding:12px;background:white;border-radius:8px}.intro h1{display:none}@media(max-width:650px){main{padding:16px}.lanes{grid-template-columns:1fr}.nav{padding:8px}h2{font-size:23px}th,td{padding:9px;min-width:120px}.branchbox{padding:16px}}@media print{.nav,.branch-controls{display:none}body{background:white}section[hidden]{display:block!important}table{display:table;font-size:10px}th,td{min-width:0;padding:5px}.branchbox{break-inside:avoid}}'''
branches='''<div class="branchbox"><h2>两台车 · 同住，不必同路线</h2><p class="caption">这是活动分流示意，不是地理比例图；住宿锚点保持，分支均待选择。</p><div class="branch-controls" role="group" aria-label="查看分流日期"><button type="button" data-branch="02" aria-pressed="false">10/2 天空岛</button><button type="button" data-branch="03" aria-pressed="true">10/3 麦卡伦</button><button type="button" data-branch="04" aria-pressed="false">10/4 球后</button></div><div id="branch-content" aria-live="polite"></div><noscript><p>10/3：你的车去麦卡伦；朋友的车去Loch Ness、铁路或湖泊；19:00在Boat会合。完整线路见下方。</p></noscript></div>'''
script='''const branches={
'02':{you:['Broadford → Sligachan','Three Chimneys午餐 · 候选','Talisker已列入意向，体验待选','可选Portree 19:30剧场'],friends:['Broadford → Storr或Quiraing','各自午餐，或Carbost会合','Talisker自选参加／继续山景','回Broadford休息'],end:'同住Broadford；看戏的人晚归，不要求所有人同行。'},
'03':{you:['08:00 Broadford出发','Loch Ness短停 + 午餐','14:00麦卡伦候选：至少3小时','约18:15–18:30抵达Boat'],friends:['08:30–09:00 Broadford出发','Loch Ness + 午餐','铁路15:28–16:19，或Tomatin／湖泊','入住与休息'],end:'约19:00 The Boat Country Inn晚餐会合，餐位待订。'},
'04':{you:['09:20 Boat · 待最终确认','完整球局 + 午餐','Loch Morlich／独立南下／Speyside','5–6日按个人方向延长'],friends:['09:20 Boat · 待最终确认','16:00到站要求与18洞冲突','先解决提前离场，不能等你游玩','还车 → Glasgow车站'],end:'朋友火车约束不绑你的车；他们仍须先解决球局与返程冲突。'}};
function lane(title,nodes,cls){return '<div class="lane '+cls+'"><h3>'+title+'</h3><div class="nodes">'+nodes.map(x=>'<div class="node">'+x+'</div>').join('<div class="arrow" aria-hidden="true">↓</div>')+'</div></div>'}
function drawBranch(key){const b=branches[key];document.getElementById('branch-content').innerHTML='<div class="lanes">'+lane('你的车',b.you,'')+lane('朋友的车 · 可选',b.friends,'friend')+'</div><div class="rendezvous">'+b.end+'</div>';document.querySelectorAll('[data-branch]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.branch===key)));}
document.querySelectorAll('[data-branch]').forEach(x=>x.addEventListener('click',()=>drawBranch(x.dataset.branch)));drawBranch('03');
function filter(key,scroll){document.querySelectorAll('section[data-day]').forEach(x=>x.hidden=key!=='all'&&x.dataset.day!==key);document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.filter===key)));if(scroll&&key!=='all'){document.getElementById('day-'+key).scrollIntoView({behavior:'smooth'});history.replaceState(null,'','#day-'+key);}else if(key==='all'){history.replaceState(null,'',location.pathname);}}
document.querySelectorAll('[data-filter]').forEach(x=>x.addEventListener('click',()=>filter(x.dataset.filter,true)));
const initial=location.hash.replace('#day-','');if(document.getElementById('day-'+initial))filter(initial,false);
'''
out='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>苏格兰完整活动 · 两台车分支与个人延长</title><style>'+style+'</style></head><body><header><h1>苏格兰完整活动线路</h1><p>9/29–10/4共同旅程 · 10/5–6个人延长候选 · 2026年9月26日更新</p></header><nav class="nav" aria-label="按日期查看">'+nav+'</nav><main><p><a href="index.html">← 返回原互动地图与预算</a></p><div class="intro">'+intro+'</div>'+branches+''.join(sections)+'<p class="source-link"><a href="https://github.com/Mrpixelraf/scotland-trip/blob/main/planning/activities-handoff-2026-09-26.md">查看可供AI读取的Markdown版本</a></p></main><script>'+script+'</script></body></html>'
(ROOT/'docs/activities.html').write_text(out)
print('Built activities page:',len(out),'characters;',len(sections),'sections')
